model: 'resnet_kd'
model_depth: 50
sample_duration: 16
DATASET: 'ActivityNet'
EPOCHS: 50
Batch_Size: 10
LR: 0.01
kd: True
dampening: 0.9
momentum: 0.9
weight_decay: 0.001
nesterov: False
lr_patience: 10
n_classes: 100
LOG_SAVE_DIR: 'log'
MODEL_SAVE_DIR: '/checkpoints'
initial_scale: 1.0
mean: [114.7748, 107.7354, 99.475]
std: [38.7568578, 37.88248729, 40.02898126]
norm_value: 1
downsample: 1
alpha: 0.1
bata: 0.1