model: 'resnet'
Dimension: 3
model_depth: 50
resnet_shortcut: 'B'
sample_size: 224
sample_duration: 8
DATASET: 'covid'
EPOCHS: 60
Batch_Size: 32
step: 4
test_step: 4
kd: False
LR: 0.01
n_classes: 3
pretrain_path: False
no_cuda: False
LOG_SAVE_DIR: 'log'
MODEL_SAVE_DIR: '/checkpoints'
initial_scale: 1.0
norm_value: 1
downsample: 1
description: ''